name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install apt dependencies
        run: |
          sudo apt-get install -y \
            libgtest-dev \
            protobuf-compiler

      - name: Install python dependencies
        run: |
          sudo pip3 install \
            psutil

      - uses: education/autograding@v1